cache:
  - c:\cargo\registry
  - c:\cargo\git

init:
  - mkdir c:\cargo
  - mkdir c:\rustup
  - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\rbxlx-to-rojo

environment:
  CARGO_HOME: "c:\\cargo"
  RUSTUP_HOME: "c:\\rustup"
  CARGO_TARGET_DIR: "c:\\projects\\rbxlx-to-rojo\\target"
  global:
    PROJECT_NAME: rbxlx-to-rojo
    RUST_BACKTRACE: full
  matrix:
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      BITS: 64

matrix:
  fast_finish: true

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V

# Hack to work around a harmless warning in Appveyor builds?
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo test --verbose

before_deploy:
  # Generate artifacts for release
  - cargo build --release --bin rbxlx-to-rojo --features cli
  - appveyor PushArtifact target\release\rbxlx-to-rojo.exe

deploy:
  description: 'Automatically deployed release'
  # All the zipped artifacts will be deployed
  artifact: /.*\.exe/
  auth_token:
    secure: UjSht2BayAT7CT+vcoJRKQUMJwTU9XJIYyWOFRStg4NOAWylm1x3ukut8a4BryWX
  provider: GitHub
  # deploy when a new tag is pushed and only on the stable channel
  on:
    CHANNEL: stable
    appveyor_repo_tag: true

branches:
  only:
    - /^\d+\.\d+\.\d+$/
    - master
