[package]
name = "rbxlx-to-rojo"
version = "0.1.0"
authors = ["Kampfkarren"]
edition = "2018"

[dependencies]
rbx_dom_weak = "1.5"
rbx_xml = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"